language: node_js
sudo: false
node_js:
- '0.10'
- '0.12'
- '4.0'
matrix:
  allow_failures:
  - node_js: '4.0'
cache:
  directories:
  - node_modules
before_script:
- npm install -g grunt-cli
script:
- if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_BRANCH == master && $TRAVIS_NODE_VERSION
  == '0.10' ]]; then npm run travis; else npm test; fi;
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  skip_cleanup: true
  provider: npm
  email: devsupport@familysearch.org
  api_key:
    secure: eN10cNmYYbqWqtRIOzJPu1Ske+b4b21IvP1m1+LzFRfwZx7HfXxq4CQzArkLXNT9qzPrdUPEXWC6Ll4qaK13z38c7rN3oDlQouOJlDmuPRVst+O/VVvclMPB/FqQiG27fN7nmg+z9vOYn44L/FkIhAz0o3+as4d765zvksxDPkQ=
  on:
    repo: FamilySearch/familysearch-javascript-sdk
    condition: $TRAVIS_NODE_VERSION == '0.10'
