language: node_js
node_js:
- '0.10'
env:
  global:
    secure: gwZrOCs5mOukCgPdj1nIqcIAUkw1X7Cy5aa7q1Ofl3mOYLVML7SFKOC8UpfqSDWd+9mLfClYOcy0brgYcco4D16ETWXCtm67WAH8YyOsr/IVKPVCKkwbG5dK0q/9ecjUa+im0/mBw+gprQUObYKADZI8EG6tPYjTTznqDU+ZXvU=
cache:
  directories:
  - node_modules
before_script:
- npm install -g grunt-cli
- git fetch origin gh-pages:gh-pages
script:
- if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_BRANCH == master ]]; then npm run
  travis; else npm test; fi;
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: npm
  email: devsupport@familysearch.org
  api_key:
    secure: ghK/nKkdR1VUkhQEIdrdjLnkYtJlTv+uMDnnvDmNdaGg4INdIKtL/c21PR0wr0Tp+7v1qvJOH/snwwdMVjUxuBDD8OYsSosxNQtvd3H49+Ao4vgKxl5lN7+0/LLM81YhuZq6+zZMHMrssGeyIzlPigccgJWACcWap78Elhp4Tpw=
  on:
    repo: FamilySearch/familysearch-javascript-sdk
